Repository scalecube/scalecube-gateway, pull requests merged in 2018-09, with the labels that each got.

#133 Calculate message trip time
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/AbstractBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/BroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/InfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/InfiniteStreamWithRateBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/RequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageCodecMicrobenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageDecoderMicrobenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageEncoderMicrobenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedInfiniteStreamWithRateBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedMicrobenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/remote/RemoteBenchmarksState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/remote/RemoteInfiniteStreamWithRateBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/standalone/StandaloneInfiniteStreamWithRateBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/standalone/StandaloneMicrobenchmarkState.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/ClientMessage.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/rsocket/RSocketClientTransport.java
  Examples/src/main/java/io/scalecube/gateway/benchmarks/BenchmarksService.java
  Examples/src/main/java/io/scalecube/gateway/benchmarks/BenchmarksServiceImpl.java
  RSocketWebsocket/src/main/java/io/scalecube/gateway/rsocket/websocket/RSocketWebsocketAcceptor.java
  Tests/src/test/resources/index.html
  pom.xml
Labels: ready for review

#141 Changed dockerfiles
  Config/src/main/java/io/scalecube/gateway/config/GatewayConfigRegistry.java
  Examples/src/main/resources/config/config.properties
  ExamplesRunner/Dockerfile
  ExamplesRunner/src/main/java/io/scalecube/gateway/examples/ExamplesConfig.java
  ExamplesRunner/src/main/java/io/scalecube/gateway/examples/ExamplesRunner.java
  ExamplesRunner/src/main/resources/config-examples.properties
  GatewayRunner/Dockerfile
  GatewayRunner/src/main/java/io/scalecube/gateway/GatewayRunner.java
  GatewayRunner/src/main/java/io/scalecube/gateway/config-gateway.properties
  GatewayRunner/src/main/resources/config-gateway.properties
Labels: ready for review

#101 Feature/clientsdk p2 reactor websocket
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/AbstractBenchmarkState.java
  ClientSdk/pom.xml
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/Client.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/ClientCodec.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/ClientMessage.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/ClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/RemoteInvocationHandler.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/codec/ClientMessageCodec.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/rsocket/RSocketClientCodec.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/rsocket/RSocketClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/Signal.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketClientCodec.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketSession.java
  ClientSdk/src/test/java/io/scalecube/gateway/clientsdk/rsocket/RSocketClientSdkTest.java
  ClientSdk/src/test/resources/log4j2-test.xml
  Examples/src/main/java/io/scalecube/gateway/examples/GreetingRequest.java
  Tests/src/test/java/io/scalecube/gateway/AbstractGatewayExtension.java
  Tests/src/test/java/io/scalecube/gateway/rsocket/RSocketClientSdkDisconnectTest.java
  Tests/src/test/java/io/scalecube/gateway/rsocket/RsocketGatewayExtension.java
  Tests/src/test/java/io/scalecube/gateway/websocket/WebsocketExtension.java
  Tests/src/test/java/io/scalecube/gateway/websocket/WebsocketGatewayExtension.java
  Tests/src/test/java/io/scalecube/gateway/websocket/WebsocketGatewayTest.java
  Tests/src/test/java/io/scalecube/gateway/websocket/WebsocketServerTest.java
  Websocket/pom.xml
  Websocket/src/main/java/io/scalecube/gateway/websocket/GatewayWebsocketAcceptor.java
  Websocket/src/main/java/io/scalecube/gateway/websocket/WebsocketSession.java
  pom.xml
Labels: enhancement, work in progress

#147 Decouple GatewayWebsocketAcceptor from WebSocketFrame
  Websocket/src/main/java/io/scalecube/gateway/websocket/GatewayWebsocketAcceptor.java
  Websocket/src/main/java/io/scalecube/gateway/websocket/WebsocketSession.java
Labels: ready for review

#145 Added websocket scenarios and refactoring
  Benchmarks/pom.xml
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/AbstractBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageCodecBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageDecoderBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/codec/GwMessageEncoderBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/DistributedBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/rsocket/DistributedBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/rsocket/DistributedInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/rsocket/DistributedRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/websocket/DistributedBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/websocket/DistributedInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/websocket/DistributedRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/RemoteBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/rsocket/RemoteBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/rsocket/RemoteInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/rsocket/RemoteRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/websocket/RemoteBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/websocket/RemoteInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/remote/websocket/RemoteRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedMicrobenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/distributed/DistributedRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/remote/RemoteBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/remote/RemoteInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/remote/RemoteRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/standalone/StandaloneBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/standalone/StandaloneInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/rsocket/standalone/StandaloneRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/StandaloneBenchmarkState.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/rsocket/StandaloneBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/rsocket/StandaloneInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/rsocket/StandaloneRequestOneBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/webscoket/StandaloneBroadcastStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/webscoket/StandaloneInfiniteStreamBenchmark.java
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/standalone/webscoket/StandaloneRequestOneBenchmark.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/Client.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/ClientSettings.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketSession.java
  Examples/src/main/java/io/scalecube/gateway/benchmarks/BenchmarksServiceImpl.java
  Websocket/src/main/java/io/scalecube/gateway/websocket/GatewayWebsocketAcceptor.java
Labels: work in progress

#156 Avoid send empty buffer
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/http/HttpClientCodec.java
Labels: bug, ready for review

#157 Add HTTP gateway to distributed benchmark
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/DistributedBenchmarkState.java
Labels: ready for review

#159 Add member dns name support in runners
  Benchmarks/src/main/java/io/scalecube/gateway/benchmarks/distributed/DistributedBenchmarkState.java
  ExamplesRunner/src/main/java/io/scalecube/gateway/examples/ExamplesRunner.java
  ExamplesRunner/src/main/resources/config-examples.properties
  GatewayRunner/src/main/java/io/scalecube/gateway/GatewayRunner.java
  GatewayRunner/src/main/java/io/scalecube/gateway/config-gateway.properties
  GatewayRunner/src/main/resources/config-gateway.properties
  Tests/src/test/java/io/scalecube/gateway/AbstractGatewayExtension.java
  pom.xml
Labels: ready for review

#162 Fixed support long data for HTTP
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/http/HttpClientTransport.java
  Http/src/main/java/io/scalecube/gateway/http/GatewayHttpAcceptor.java
  Tests/src/test/java/io/scalecube/gateway/http/HttpGatewayTest.java
  Tests/src/test/java/io/scalecube/gateway/rsocket/RSocketWebsocketGatewayTest.java
  Tests/src/test/java/io/scalecube/gateway/websocket/WebsocketGatewayTest.java
Labels: ready for review

#158 Add headers to gateway message
  Websocket/src/main/java/io/scalecube/gateway/websocket/GatewayWebsocketAcceptor.java
  Websocket/src/main/java/io/scalecube/gateway/websocket/message/GatewayMessage.java
  Websocket/src/main/java/io/scalecube/gateway/websocket/message/GatewayMessageCodec.java
Labels: ready for review

#163 Fixed docker support
  Benchmarks/pom.xml
  ExamplesRunner/pom.xml
  GatewayRunner/pom.xml
  pom.xml
Labels: ready for review

#170 Use parallel scheduler instead of single for publishOn
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/http/HttpClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/rsocket/RSocketClientTransport.java
  ClientSdk/src/main/java/io/scalecube/gateway/clientsdk/websocket/WebsocketClientTransport.java
Labels: ready for review
